FROM node:22-alpine AS frontend_builder
WORKDIR /app

COPY frontend/package*.json /app/
RUN npm ci

COPY frontend /app

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
