# Generated by Django 5.2.9 on 2026-01-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chat_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_convers_d2b392_idx',
            old_name='core_message_conv_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_convers_57fc9a_idx',
            old_name='core_message_conv_read_idx',
        ),
    ]
