# Generated by Django 5.2.9 on 2026-04-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_favoriteservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'master'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'master'}, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор'), ('master', 'Мастер')], max_length=20),
        ),
    ]
