# Generated by Codex on 2026-04-08
from django.db import migrations


DEFAULT_ADMIN_EMAIL = "admin@admin.admin"


def split_roles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("core", "UserProfile")

    admin_profiles = UserProfile.objects.filter(role="admin").select_related("user")
    for profile in admin_profiles:
        user = profile.user
        if not user:
            continue
        if user.is_superuser or (user.email or "").lower() == DEFAULT_ADMIN_EMAIL:
            continue
        profile.role = "master"
        profile.save(update_fields=["role"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_booking_master_alter_service_masters_and_more"),
    ]

    operations = [
        migrations.RunPython(split_roles, migrations.RunPython.noop),
    ]
